### ISSUE TITLE
Error: "Unable to refresh the access token"

### ISSUE THREAD

**Issue by jostrasser** [guidone/node-red-contrib-netatmo-dashboard#25]
Hi,

today Netatmo disabled the old auth method.
Since this moment I am getting the following error: "Unable to refresh the access token":

![image](https://user-images.githubusercontent.com/14274103/232525337-cae7fe57-af31-404d-8582-f5345f12cf06.png)

If I manually generate a fresh token it is working only one time to connect.
Any ideas how to solve this?

Thanks!

**Comment by jostrasser** [comment]
Got the following information from Netatmo DEV Support yesterday:

```
Indeed we now change the refresh_token value each time a new /token request is performed
You maybe didn't receive our email communications about this...
```

And today:

`Teams performed a rollback. Indeed some "legit" third-party apps were unable to perform /token calls. They are investigating to find the root cause, fix it, and re-deploy the change`

So I think the `Unable to refresh the access token` was related to the platform issues / changes from Netatmo.
Waiting for the "next change".

**Comment by ohrenweide** [comment]
Same problem here, thanks for opening the issue.

**Comment by electrontube** [comment]
Any progress here?

**Comment by jostrasser** [comment]
> Any progress here?
> 
> 

I think at the moment everything should be working as expected (for me all is working fine) because Netatmo has undo the authentication method / the last changes. I have now inquired with Netatmo about when the transition is now planned. As soon as Netatmo redo the authentication changes, there could be problems again.

If you are running into the error right now try to generate fresh keys. They should solve the issue. 

I'll keep you posted about the Netatmo DEV Support feedback.

**Comment by electrontube** [comment]
> > Any progress here?
> 
> I think at the moment everything should be working as expected (for me all is working fine) because Netatmo has undo the authentication method / the last changes. I have now inquired with Netatmo about when the transition is now planned. As soon as Netatmo redo the authentication changes, there could be problems again.
> 
> If you are running into the error right now try to generate fresh keys. They should solve the issue.
> 
> I'll keep you posted about the Netatmo DEV Support feedback.

Generating completely new keys did the trick, everything is working again now!

Thanks for the hint!

**Comment by kevinpato72** [comment]
Hi,
Same issue here since this morning. 
Generating completely new keys did nothing...

**Comment by ohrenweide** [comment]
> Hi,
> Same issue here since this morning.
> Generating completely new keys did nothing...

It was the same for me... until I noticed that the app had been disabled for some reason. When I reactivated it, everything worked again.
So you may also want to check the 'app status' of your app in your developer account.

**Comment by ohrenweide** [comment]
> Hi,
> Same issue here since this morning.
> Generating completely new keys did nothing...

It was the same for me. Also, the app had been disabled for some reason (check your app's "app status" in your developer account).

A newly generated refresh token only worked for the first call of the node. Subsequent calls returned the error "Unable to refresh the access token".

**Comment by jostrasser** [comment]
Same here... :(

**Comment by todrees1967** [comment]
Same here since the afternoon hours today ......

**Comment by jostrasser** [comment]
Contacted Netatmo DEV Support to get more details about the platform (if they made changes).
I´ll keep you posted.

**Comment by AleksCee** [comment]
I have debug the response and this show the error: '{"error":"invalid_grant"}' 
On the netatmo page this means:

> This is caused by an URI issue. Either you're not specifying the same URI in your calls; \ror the one you specified didn't match the one you associated with your app in your account settings.

But there is no URI parameter in the refresh_token request. I have ask the at netatmo, too.

**Comment by jostrasser** [comment]
@guidone 

Info from Netatmo DEV Support:

```
We just did a modification on the token retrieval process :
 
When you refreshed an access_token using the associated endpoint [https://api.netatmo.com/oauth2/token, Netatmo servers](https://api.netatmo.com/oauth2/token,%C2%A0Netatmo%C2%A0servers) responded with a couple of tokens : an access_token and a refresh_token. If the previous access_token was still valid, the refresh_token value was never renewed
 
Starting from the 04/12/2023, this behavior changed to be compliant with the recommendations of the [RFC of the OAuth2 Authorization Framework](https://www.rfc-editor.org/rfc/rfc6749) (section 10.4) and improving the security of the data of our users
When refreshing tokens, access_token and refresh_token values will be automatically renewed and former tokens invalidated
 
So, if you do not update and use the new refresh_token value when refreshing your access_token, your users will be disconnected after 3 hours and you will retrieve an “invalid_grant” error
To fix it, you need to update the tokens value as soon as you get the newly generated ones.
```

**Comment by jostrasser** [comment]
Additional info from Netatmo:

```
The access_token must be refreshed every 3 hours (10800 seconds). This has always been the case
The difference was that if you refreshed your access_token before its expiration, refresh_token value always remained the same. If you wanted to refresh it but after expiration, the refresh_token value changed
 
Now, the 2 values change at each new /token request. So, you must catch the new generated refresh_token value each time a new request is done to the endpoint, and perform the next /token call with this new value
```

**Comment by jostrasser** [comment]
Another update from Netatmo. 
This is the reason why all the apps, plugins, integrations are back working again:

`Indeed, teams had to do a rollback to fix a problem for multiple connections (if a 2nd device connects, it asks for a token and invalidates the access for the 1st connected device). I reported that it was a problem for third-party apps
The plan is still to put in place this change. They are working on a solution, but I don't have for now more information about a release date`

I requested detailed information when the next change will take place.

**Comment by FrodoVDR** [comment]
Since yesterday it no longer works, after entering a new refresh token you get data once after which the token is invalid.

**Comment by jostrasser** [comment]
> Since yesterday it no longer works, after entering a new refresh token you get data once after which the token is invalid.

Definitely related to this:

> Hello Johannes,
> 
> We just did a modification on the token retrieval process :
> 
> When you refreshed an access_token using the associated endpoint [https://api.netatmo.com/oauth2/token, Netatmo servers](https://api.netatmo.com/oauth2/token,%C2%A0Netatmo%C2%A0servers) responded with a couple of tokens : an access_token and a refresh_token. If the previous access_token was still valid, the refresh_token value was never renewed
> 
> Starting from yesterday, this behavior changed to be compliant with the recommendations of the RFC of the OAuth2 Authorization Framework (section 10.4) and improving the security of the data of our users
> When refreshing tokens, access_token and refresh_token values will be automatically renewed and former tokens invalidated
> 
> So, if you do not update and use the new refresh_token value when refreshing your access_token, your users will be disconnected after 3 hours and you will retrieve an “invalid_grant” error
> To fix it, you need to update the tokens value as soon as you get the newly generated ones
> 
> Please note that we are not linked to third-party apps or to their developments. It’s up to them to follow our token renewal process
> 
> Have a good day,
> Leslie - Community Manager

The fact is: this plugin is broken now.

**Comment by kailausberg** [comment]
Use this great node-red flow instead:  https://gist.github.com/matz33/843165d0046cac534864b65e633801a5

It works like a charm with the new api authorization process!

**Comment by jostrasser** [comment]
Definitely, just wanted to refer to it ;)
I believe that this plugin has simply reached EOL and we have to accept that (= looking for alternatives).
With these words I will close this issue now.

**RIP node-red-contrib-netatmo-dashboard**
